### ISSUE TITLE
Adding hotkeys to save changes on an image

### ISSUE THREAD

**Issue by Abcfsa** [hirune924/Streamlit-Image-Annotation#8]
Hello dear developer,currently I'm working on a task to make annotations on some hundred images,and I found it a little inconvenient having to click that "complete" button every time I finish my work on an image.So is it possible to save the changes on an image by pressing a hotkey or something?Thanks.

**Comment by hirune924** [comment]
Thank you for your suggestion. The hotkey feature is a good idea, I would like to add it in the future.

**Comment by hirune924** [comment]
now I add this option. you can use "space key" for complete
https://github.com/hirune924/Streamlit-Image-Annotation/tree/90ffaa3401a42b3586dc181e9cb7c9f0239aafbf
https://st-image-annotation.streamlit.app/
